const express=require("express")
const database=require("./database")
const loginRouter=require("./Admin/login")
const adminnote=require("./Admin/adminnote")
const dotenv=require("dotenv")
const cors=require("cors")
const userLogin=require("./User/login")
const usernote=require("./User/userlogin")

dotenv.config()
const app=express()
app.use(express.json())
app.use(cors())
app.use(loginRouter)
app.use(adminnote)
app.use(userLogin)
app.use(usernote)
app.listen(3000,()=>{
    console.log("Server running at port 3000");
})